gText_Birch_Welcome:: @ 82C897B
	.string "Welcome to the world of Pokémon!\p"
	.string "My name is Professor Birch.\p"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "This beautiful creature is\n"
	.string "known as a “Pokémon.”\l"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "Despite our fondness, we don't\n"
	.string "know everything about Pokémon.\p"
	.string "And there are some people\n"
	.string "who exploit Pokémon for profit.\p"
	.string "To unravel Pokémon mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "And you are?$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Which Pokémon trainer\n"
	.string "do you want to play as?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "Ah, okay!\p"
	.string "Nice to meet you!\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of Pokémon where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "I'll be expecting you later.\n"
	.string "Come see me in my Pokémon Lab.\p"
	.string "$"
